import { Cairo, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Cairo({
  subsets: ["arabic"],
  variable: "--font-cairo",
    display: "swap",
});

const geistMono = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
}); 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Cairo.variable} ${Poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
